### ISSUE TITLE
Instead of having IndexX.elm files, use a folder

### ISSUE THREAD

**Issue by eeue56** [rluiten/elm-text-search#1]
- Index.elm
- IndexDefaults.elm
- IndexLoad.elm 
- IndexModel.elm
- IndexUtils.elm
- IndexVector.elm

should be
- Index.elm
- Index/Defaults.elm
- Index/Load.elm 
- Index/Model.elm
- Index/Utils.elm
- Index/Vector.elm

**Comment by rluiten** [comment]
Done in 2.0.0 release
