### ISSUE TITLE
Can't index or search for "one" (or: maybe filter stopwords before stemming?)

### ISSUE THREAD

**Issue by tgecho** [rluiten/elm-text-search#10]
In my initial testing, I got an error when I searched for the text "one". As far as I can tell, it looks like [`processTokens` transforms the tokens before filtering them](https://github.com/rluiten/elm-text-search/blob/672d3f7cbaeb9b2b1f8f45099ca98f628c06db98/src/Index/Utils.elm#L61). In this case, "one" becomes "on" and is filtered out as a stopword.

I don't know much about this stuff, but it would seem to make sense to filter out stopwords first? This seems to be what lunr.js does according to [this comment](https://github.com/olivernn/lunr.js/issues/194#issuecomment-172889475)

Example: https://ellie-app.com/346jy8VmsMXa1/0

**Comment by rluiten** [comment]
That is a good example of the problem I believe, thank you.

I do believe I will need to modify the behavior to filter the original stop word lists as per your example. I was looking for some clarification at the time as you found in that comment, but I never got beyond that point.

I am not to sure at moment on how much work there will be in the change required but I hope to explore it more in the next few days.

**Comment by tgecho** [comment]
One other thing to keep in mind is that the word "one" in the doc isn't even indexed. If you change the doc text to simply "one" an `Err "Error after tokenisation there are no terms to index."` is returned.

I haven't tried to follow all of the ramifications, so I apologize for speaking from a position of relative ignorance. Might it make sense to combine the `TransformFunc` and `FilterFunc` types into a single `String -> Maybe String`?

This could allow a fully custom single list of transform functions which could filter and/or transform as the user needs. From poking around, it seems that there may be some valid use cases for doing it both ways.

I'm happy to attempt a PR if this sounds interesting/feasible and you don't have much short term.

Thanks for the great library!

**Comment by rluiten** [comment]
I have published a version with a fix for the filter behavior 4.0.0.
I briefly tried to see if Ellie had picked up the change already but it had not. 
I assume it takes a while for Ellie to get new package versions.

**Comment by tgecho** [comment]
That did the trick! Looks like Ellie pins the library versions. Here's one with an update to 4.0.0 that confirms the fix: https://ellie-app.com/346jy8VmsMXa1/1

Thank you so much!
