### ISSUE TITLE
Replace error strings with union types?

### ISSUE THREAD

**Issue by tgecho** [rluiten/elm-text-search#11]
I'm trying to handle some of the errors in certain ways, but having to switch on strings is a bit of a bummer. Would you be interested in a PR that replaces the string error messages with some custom  union types?

I'm picturing something verbose but straightforward like these (we could sort out the details to your taste):

```elm
type AddError
    = UniqueRefIsEmpty
    | NoTermsToIndexAfterTokenisation
    | DocAlreadyExists

type RemoveError
    = UniqueRefIsEmpty
    | DocIsNotInIndex

type SearchError
    = IndexIsEmpty
    | QueryIsEmpty
    | NoTermsToSearchAfterTokenisation
```

**Comment by rluiten** [comment]
That's a good idea, much better than strings.
Can add something that converts any given error back to a string for those that want a string.

As a starting point the ones you outline seem like a good place to start.

**Comment by kephas** [comment]
That would make the type system tell us we are out of sync if a new kind of error is added in a new version of the lib.

**Comment by rluiten** [comment]
I have added 3 new functions addT, removeT, searchT that return results using the above types suggested.
