### ISSUE TITLE
Errors when searching for the keyword "a"or"A" but not other single characters.

### ISSUE THREAD

**Issue by mlebow** [rluiten/elm-text-search#15]
When a search is done for the single letter "a" it produces the error:  "Error after tokenisation there are no terms to search for."

This can be reproduced by changing the search term in the MultipleAddSearch.elm example to either "a" or "A".

"A" was the only character I found that caused a problem.  Other single letters or numbers work correctly.

**Comment by mlebow** [comment]
Ah, this error occurs whenever one of the Stop Words are searched for.  I guess this is intended behavior.

**Comment by rluiten** [comment]
Cheers, all good learning :).
Possibly improving the error message might be worth it here?

Maybe to something like that - `Error after tokenisation there are no terms to search for. maybe your input contained only stop words`
