### ISSUE TITLE
Usage example for indexing an array of records?

### ISSUE THREAD

**Issue by joakimk** [rluiten/elm-text-search#3]
In the docs you only index one record, but a search engine won't be very useful unless you can index a lot of them.

What would you think of adding an example of how to index an array of records?

**Comment by rluiten** [comment]
Most search engines will add a document at a time and save the index, and reload it later.
So you only need the index to do a search on the client side, and once you found the document id you then retrieve the document Id.

However I do think having a multiple add document interface is a good idea.
So I am adding 2 variants to the API and adding an example

**Comment by rluiten** [comment]
I have published 2.1.0.

Added 'addDocs' function that adds a list of documents to index.
Added an example for it at as well.

**Comment by joakimk** [comment]
In my case I'm building a FAQ search engine where the source data is sufficiently small to be present at page load.

I've tried this feature and it works. I've found another issue though that I reported.
