### ISSUE TITLE
Can not find anything when two records have a similar text

### ISSUE THREAD

**Issue by joakimk** [rluiten/elm-text-search#4]
I'm indexing a FAQ archive.

In my prototype I have "Question1" and "Question2" and when I search for "Q" I get nothing, but if I rename "Question2" to "Puestion2", then I find "Question1". This seems like a bug.

**Comment by rluiten** [comment]
I have created a test here that is showing that behaviour.
I am re reading parts of lunr.js now, as it does not exhibit this behaviour.

I think it has to do with how final results are aggregated.

**Comment by rluiten** [comment]
This is now fixed in 2.1.1 I believe.
Turns out it was a problem in result aggregation.
I had just missed a piece of the puzzle and I was throwing away results in some cases with set intersections. I had a test case for this area but its expected result was wrong.

**Comment by joakimk** [comment]
My prototype app using your library (also my first elm project) is on github now in case you're curious: https://github.com/joakimk/help-search.

**Comment by rluiten** [comment]
Cool, had a look :) 
Thanks for your feed back on this package.
