### ISSUE TITLE
addOrUpdate function

### ISSUE THREAD

**Issue by brunogirin** [rluiten/elm-text-search#8]
I have a use case where I receive documents as part of a HTTP GET that may or may not already be in my index so I'd like to add them if they're not in and update if they're already in. The way I do this at the moment is to add and if this results in an error, update. It would be nice to have a `addOrUpdate` capability instead.

**Comment by rluiten** [comment]
I published 3.1.0 with addOrUpdate function.

**Comment by brunogirin** [comment]
Awesome, thanks!
