### ISSUE TITLE
How do I use CodecIndexRecord?

### ISSUE THREAD

**Issue by avh4** [rluiten/elm-text-search#9]
I've encoded an Index to JSON, and then decoded it, which produces a `CodecIndexRecord`.  How do I use that to get back an Index?

**Comment by rluiten** [comment]
You can look at `Index.Load` which drives the decoder to recreate an Index, this Module is not exported.
Specifically `loadIndexFull` does a conversion with other function that check a CodecIndexRecord for validity to create an Index.

If you use the simplest external api to save.
* `ElmTextSearch.storeToValue` 
* `ElmTextSearch.storeToString` 

If you use the simplest external api to load.
* `ElmTextSearch.fromString`
* `ElmTextSearch.fromValue`

**Comment by avh4** [comment]
Thanks!  `storeToValue` and `fromValue` worked for me :)
